package:
  name: dasel
  version: 3.3.1
  epoch: 1
  description: A CLI tool to query and modify data structures
  copyright:
    - license: MIT

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout
      - ca-certificates-bundle
      - go
      - patch

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/TomWright/dasel
      tag: v3.3.1
      expected-commit: fba653c7f248aff10f2b89fca93929b64707dfc8

  - uses: patch
    with:
      patches: CVE-2026-33320.patch

  - runs: |
      CGO_ENABLED=0 go build -ldflags="-s -w" -o dasel ./cmd/dasel
      mkdir -p ${{targets.destdir}}/usr/bin
      install -m 755 dasel ${{targets.destdir}}/usr/bin/dasel

test:
  environment:
    contents:
      repositories:
        - https://dl-cdn.alpinelinux.org/alpine/edge/main
        - https://dl-cdn.alpinelinux.org/alpine/edge/community
      packages:
        - busybox
        - dasel
  pipeline:
    - runs: |
        dasel version